create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_photos (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  title_en text,
  title_uk text,
  meta text,
  meta_en text,
  meta_uk text,
  text text,
  text_en text,
  text_uk text,
  theme text not null default 'sunset'
    check (theme in ('sunset', 'sunrise', 'clouds', 'moon', 'stars', 'city')),
  gradient text,
  image_url text not null,
  storage_path text,
  frame text not null default '4 / 5',
  position text not null default '50% 50%',
  photo_date date,
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view', 'photo_view')),
  photo_id uuid references public.gallery_photos(id) on delete set null,
  visitor_id text,
  path text,
  language text,
  viewport_width integer,
  viewport_height integer,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists gallery_photos_set_updated_at on public.gallery_photos;
create trigger gallery_photos_set_updated_at
before update on public.gallery_photos
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where email = auth.jwt() ->> 'email'
  );
$$;

alter table public.admin_users enable row level security;
alter table public.gallery_photos enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (public.is_admin());

drop policy if exists "Public can read published photos" on public.gallery_photos;
create policy "Public can read published photos"
on public.gallery_photos
for select
to anon, authenticated
using (published = true or public.is_admin());

drop policy if exists "Admins can insert photos" on public.gallery_photos;
create policy "Admins can insert photos"
on public.gallery_photos
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update photos" on public.gallery_photos;
create policy "Admins can update photos"
on public.gallery_photos
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete photos" on public.gallery_photos;
create policy "Admins can delete photos"
on public.gallery_photos
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can add analytics events" on public.analytics_events;
create policy "Anyone can add analytics events"
on public.analytics_events
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read analytics events" on public.analytics_events;
create policy "Admins can read analytics events"
on public.analytics_events
for select
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('gallery-images', 'gallery-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read gallery images" on storage.objects;
create policy "Public can read gallery images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'gallery-images');

drop policy if exists "Admins can upload gallery images" on storage.objects;
create policy "Admins can upload gallery images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'gallery-images' and public.is_admin());

drop policy if exists "Admins can update gallery images" on storage.objects;
create policy "Admins can update gallery images"
on storage.objects
for update
to authenticated
using (bucket_id = 'gallery-images' and public.is_admin())
with check (bucket_id = 'gallery-images' and public.is_admin());

drop policy if exists "Admins can delete gallery images" on storage.objects;
create policy "Admins can delete gallery images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'gallery-images' and public.is_admin());

-- After creating your Supabase Auth user, run this once with your email:
-- insert into public.admin_users (email) values ('you@example.com');
